version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: booking_app_postgres
    environment:
      POSTGRES_DB: booking_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d booking_app"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking_app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: booking_app
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
    driver: local
